name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '5 15 * * SUN'

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-20.04
    container:
      image: perldocker/perl-tester:5.32
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: auto-build-and-test-dist
      - uses: actions/upload-artifact@v2
        with:
          name: build_dir
          path: build_dir

  test-job:
    needs: build-job
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
        perl:
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - uses: actions/download-artifact@v2
        with:
          name: build_dir
          path: .

      - run: cpm install -g

      - name: Install latest perltidy
        run: cpm install -g Perl::Tidy

      - name: Set default Git config
        run: |
          git config --global init.defaultBranch master
          git config --global user.email "test@example.com"
          git config --global user.name "Test"

      - name: Run Tests
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1
        run: perl Makefile.PL && make test
